### ISSUE TITLE
Multiple issues with MultiviewXR Pipeline in Mesh sample

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de-atom-sampleviewer#607]
**Describe the bug**
When using Dx12, selecting the "Use MultiviewXR Pipeline" option in the Mesh sample results in an assert pop-up followed by the second pop-up with information that the GPU device was removed and a crashing of the Game Launcher. Also when using Vulkan user is able to select MultivieXR Pipeline without any issues but after closing the application multiple assert pop-ups are shown. The issue occurs on both Windows and Linux.

This issue should be considered as a Major.

**Steps to reproduce**
1. Launch AtomSampleViever.GameLauncher.exe.
2. Launch the Mesh sample.
3. Attempt to select the Use MultiviewXR Pipeline option.

**Expected behavior**
The sample is fully functional and remains stable.

**Actual behavior**
Multiple issues with MultiviewXR Pipeline.

**Video**

Dx12:

https://user-images.githubusercontent.com/96232062/229116080-35f45a18-2c60-4c62-84b6-eef1f186a50c.mp4

Vulkan:

https://user-images.githubusercontent.com/96232062/229116098-5606e012-b9a3-49f6-8a05-a5e0b06d7bf3.mp4

**Found in Branch**
Stabilization/2305
Development 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
o3de-atom-sampleviewer: Development (https://github.com/o3de/o3de-atom-sampleviewer/commit/873499a3772d2ede280bb28afb8d6b7301a739c9)
O3DE: Development (https://github.com/o3de/o3de/commit/7244dec1760126501947fca3a323fc638aa82a5b)
o3de-atom-sampleviewer: Stabilization/2305(https://github.com/o3de/o3de-atom-sampleviewer/commit/cee84fa2a7e85b08128271afef3c36b06284d8d7)
O3DE: Stabilization/2305 Installer build (https://o3debinaries.org/stabilization-2305/Latest/Linux/O3DE_latest.deb)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[Game.log](https://github.com/o3de/o3de-atom-sampleviewer/files/11121612/Game.log)
[error.log](https://github.com/o3de/o3de-atom-sampleviewer/files/11121613/error.log)
[error.zip](https://github.com/o3de/o3de-atom-sampleviewer/files/11121616/error.zip)

**Comment by moudgils** [comment]
This has been fixed.

**Comment by LB-HubertUberman** [comment]
@moudgils The issue still occurs on the latest Stabilization/2305 installer and o3de-atom-sampleviewer: Stabilization/2305(https://github.com/o3de/o3de-atom-sampleviewer/commit/cee84fa2a7e85b08128271afef3c36b06284d8d7) when using Vulkan. Please note that reopening the issue on our side is impossible due to lack of permissions in o3de-sample-viewer repository. Verified that issue no longer occurs when using Dx12.

**Comment by moudgils** [comment]
I would recommend opening a new issue with log/details as it sounds like a completely different problem.
